config/routes.rb
Promysql::Application.routes.draw do
    
  resources :apps
   
  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end

   root 'site#index'

end

app/models/app.rb
class App < ActiveRecord::Base
    
    belongs_to :user
    
    # ensure that a user_id is present
    validates :user_id, presence: true
    
    #ensure that a name is present and having atleast 4 characters
    validates :name, length: { minimum: 4 }, presence: true
    
    #ensures that a version is present
    validates :version, presence: true
    
    paginates_per 25    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  has_many :apps
  
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :confirmable
  
         validates :username,
         presence: true,
         uniqueness: {case_sensitive: false},
         format: {with: /\w+/}
         
         def to_param
             self.username
         end
         
         end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
    before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
  def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) do |u|
          u.permit(:username, :email, :password, :password_confirmation)
      end
      
      devise_parameter_sanitizer.for(:account_update) do |u|
          u.permit(:username, :email, :password, :password_confirmation, :current_password)
      end
  end
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
    
before_action :set_app, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!

# GET /Apps
def index
    @apps = current_user.apps.order('created_at desc').page(params[:page])
end

# GET /Apps/1
def show
end

# GET /Apps/new
def new
    @app = current_user.apps.new
end

# GET /Apps/1/edit
def edit
end

# POST /Apps
def create
    @app = current_user.apps.new(app_params)
    
    if @app.save
        redirect_to @app, notice: 'App was successfully created.'
        else
        render action: 'new'
    end
end

# PATCH/PUT /Apps/1
def update
    if @app.update(app_params)
        redirect_to @app, notice: 'App was successfully updated.'
        else
        render action: 'edit'
    end
end

# DELETE /Apps/1
def destroy
    @app.destroy
    redirect_to apps_url, notice: 'App was successfully destroyed.'
end

private
# Use callbacks to share common setup or constraints between actions.
def set_app
    unless @app = current_user.apps.where(id: params[:id]).first
        flash[:alert] = 'App not found.'
        redirect_to root_url
    end
end


def app_params
    params.require(:app).permit(:name, :version, :user_id)
end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
      if current_user
          @current_user.apps = current_user.apps.order('created_at desc').page(params[:page])
        
        else
        
        @apps = App.order('created_at desc').page(params[:page])
        end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/apps/_form.html.erb
<%= simple_form_for(@app) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :version %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<h1>Editing app</h1>

<%= render 'form' %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/index.html.erb
<h1>Listing apps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Version</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @apps.each do |app| %>
      <tr>
        <td><%= app.name %></td>
        <td><%= app.version %></td>
        <td><%= link_to 'Show', app %></td>
        <td><%= link_to 'Edit', edit_app_path(app) %></td>
        <td><%= link_to 'Destroy', app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @apps %>

<%= link_to 'New App', new_app_path %>

app/views/apps/new.html.erb
<h1>New app</h1>

<%= render 'form' %>

<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @app.name %>
</p>

<p>
  <strong>Version:</strong>
  <%= @app.version %>
</p>

<strong>User:</strong>
  <%= @app.user_id %>
</p>

<%= link_to 'Edit', edit_app_path(@app) %> |
<%= link_to 'Back', apps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
          <meta charset="utf-8" />
          <!-- Uncomment to make IE8 render like IE7 -->
          <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

          <!-- Set the viewport width to device width for mobile -->
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />

          <title><%= content_for?(:title) ? yield(:title) : "Plackal Tech" %></title>

          <%= stylesheet_link_tag    "application" %>
          <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row">
      <div class="large-12 columns">

        <!-- Navigation -->

        <div class="row">
          <div class="large-12 columns">

            <nav class="top-bar">
              <ul class="title-area">
                <!-- Title Area -->
                <li class="name">
                  <h1><a href="/">Plackal Tech</a></h1>
                </li>
              </ul>

             <section class="top-bar-section">
                <ul class="left">
             </ul>

                <!-- Right Nav Section -->
                <ul class="right">
                  <li class="divider"></li>
                  <% if current_user %>
                    <li><%= link_to 'My Apps', apps_path %></li>
                    <li class="divider"></li>

                    <li class="has-dropdown">
                      <%= link_to current_user.username, '#'%>
                      <ul class="dropdown">
                      <li><%= link_to 'Profile', edit_user_registration_path %></li>
                      <li><%= link_to 'Logout', destroy_user_session_path %></li>
                        <li class="divider"></li>
                      </ul>
                    </li>
                  <% else %>
                    <li><%= link_to 'Login', new_user_session_path %></li>
                    <li><%= link_to 'Register', new_user_registration_path %></li>
                  <% end %>
                </ul>
              </section>
            </nav>
            <!-- End Top Bar -->
          </div>
        </div>
        <!-- End Navigation -->

        <!-- Flash messages -->
        <div class="row">
          <div class="large-12 columns">
            <% if flash[:notice] %>
              <div data-alert class="alert-box success">
                <a href="#" class="close">&times;</a>
                <%= flash[:notice] %>
              </div>
            <% end %>

            <% if flash[:alert] %>
              <div data-alert class="alert-box alert">
                <a href="#" class="close">&times;</a>
                <%= flash[:alert] %>
              </div>
            <% end %>
          </div>
        </div>
        <!-- End Flash messages -->

        <!-- Content -->
        <div class="row">
          <div class="large-12 columns">
            <%= yield %>
          </div>
        </div>
        <!-- End Content -->

        <!-- Footer -->
        <footer class="row">
          <div class="large-12 columns"><hr />
            <div class="row">
              <div class="large-6 columns">
               </div>

              <div class="large-6 columns">
                <ul class="inline-list right">
                  <li><a href="http://plackal.in/about/">About</a></li>
                  <li><a href="http://plackal.in/products/">Products</a></li>
                  <li><a href="http://plackal.in/contact/">contact</a></li>
                  </ul>
              </div>
            </div>
          </div>
        </footer>
        <!-- End Footer -->

      </div>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/site/index.html.erb
<% if current_user %>
  <h2> your Latest Apps</h2>
  <table style="width: 100%">
  <tbody>
      <% @current_user.apps.each do |app| %>
        <tr>
          <td><%= link_to app.name, app.version %></td>
                 
        </tr>
      <% end %>
    </tbody>
  </table>
 
 <% else %>
  <div class="panel">
  
  <h1> Welcome To Plackal Techno Systems Private Limited</h1>
  
  <h2> Latest Apps </h2>
  <% @apps.each do |app| %>

  <p><%= link_to app.name %></p>
  
  <% end %>

    <h2>Share your Apps!</h2>
    <%= link_to "Get started today", new_user_registration_path, :class => "button button-large" %>
  </div>
  
   
    <% end %>